import $ from 'jquery'
import  '../../utils/app.scss'
import '../../components/header/header.scss'
import '../../components/header/header'
import '../../components/footer/footer.scss'
import '../../components/sign-up/sign-up'
import './registration.scss'